# -*- coding: utf-8 -*-
"""Lab3_Student_Sagar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8NqLm6iLpXQxudIuF3I7IvO3pBgKeJn
"""

import numpy as np

print("== Q1: 1D array from 10 to 50 ==")
q1 = np.arange(10, 51)
print(q1)

print("\n== Q2: 2D array of shape (3, 4) filled with zeros ==")
q2 = np.zeros((3, 4))
print(q2)

print("\n== Q3: 4x4 identity matrix ==")
q3 = np.eye(4)
print(q3)

print("\n== Q4: 20 random integers between 1 and 100 ==")
q4 = np.random.randint(1, 101, 20)
print(q4)

print("\n== Q5: 10 evenly spaced values between 0 and 1 ==")
q5 = np.linspace(0, 1, 10)
print(q5)

print("\n== Q6: First three elements of a 1D array ==")
arr6 = np.arange(10)
q6 = arr6[:3]
print(q6)

print("\n== Q7: Slice second and third rows of a 2D array ==")
arr7 = np.arange(1, 13).reshape(3, 4)
q7 = arr7[1:3]
print(q7)

print("\n== Q8: Replace all odd numbers with -1 ==")
arr8 = np.arange(1, 11)
arr8[arr8 % 2 != 0] = -1
print(arr8)

print("\n== Q9: Retrieve elements greater than 50 ==")
arr9 = np.random.randint(1, 100, 20)
q9 = arr9[arr9 > 50]
print("Original:", arr9)
print("Filtered:", q9)

print("\n== Q10: Set diagonal values of 5x5 matrix to 1 ==")
q10 = np.zeros((5, 5))
np.fill_diagonal(q10, 1)
print(q10)

print("\n== Q11: Multiply two arrays element-wise ==")
a11 = np.array([1, 2, 3])
b11 = np.array([4, 5, 6])
q11 = a11 * b11
print(q11)

print("\n== Q12: Add scalar value 5 to each element ==")
arr12 = np.array([10, 20, 30])
q12 = arr12 + 5
print(q12)

print("\n== Q13: Square root of all elements ==")
arr13 = np.array([1, 4, 9, 16])
q13 = np.sqrt(arr13)
print(q13)

print("\n== Q14: Sum, mean, std deviation ==")
arr14 = np.array([10, 20, 30, 40])
print("Sum:", np.sum(arr14))
print("Mean:", np.mean(arr14))
print("Std Dev:", np.std(arr14))

print("\n== Q15: Reshape 1D array of 16 elements into 4x4 matrix ==")
arr15 = np.arange(1, 17)
q15 = arr15.reshape(4, 4)
print(q15)

print("\n== Q16: Boolean array where values > 25 are True ==")
arr16 = np.array([10, 30, 25, 40])
q16 = arr16 > 25
print(q16)

print("\n== Q17: Replace negative numbers with 0 using np.where ==")
arr17 = np.array([-5, 10, -3, 7])
q17 = np.where(arr17 < 0, 0, arr17)
print(q17)

print("\n== Q18: Count elements divisible by 3 ==")
arr18 = np.arange(1, 31)
q18 = np.sum(arr18 % 3 == 0)
print("Count:", q18)

print("\n== Q19: Stack two arrays vertically and horizontally ==")
a19 = np.array([[1, 2], [3, 4]])
b19 = np.array([[5, 6], [7, 8]])
v_stack = np.vstack((a19, b19))
h_stack = np.hstack((a19, b19))
print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)

print("\n== Q20: Flatten multi-dimensional array into 1D ==")
arr20 = np.array([[1, 2], [3, 4]])
q20 = arr20.flatten()
print(q20)

